export const eventList2024 = [
  {
    id: 1,
    date: '08.03.2024',
    event: 'Махашиваратри',
    done: true,
    link: '/gallary/mahashivaratriphoto2024',
  },
  {
    id: 2,
    date: '05.04.2024',
    event: 'Экадаши Папамочани',
    done: true,
    link: '',
  },
  {
    id: 3,
    date: '07.04.2024',
    event: 'Брахмананда-джаянти',
    done: true,
    link: '/gallary/brahmanandajayantiphoto2024',
  },
  {
    id: 4,
    date: '08.04.2024',
    event: 'Весеннее Наваратри',
    done: true,
    link: '',
  },
  {
    id: 5,
    date: '19.04.2024',
    event: 'Экадаши Камада',
    done: true,
    link: '',
  },
  {
    id: 6,
    date: '04.05.2024',
    event: 'Экадаши Варутхини',
    done: true,
    link: '',
  },
  {
    id: 7,
    date: '10.05.2024',
    event: 'Акшая-тритья',
    done: true,
    link: '',
  },
  {
    id: 8,
    date: '12.05.2024',
    event: 'Шанкара-джаянти',
    done: true,
    link: '',
  },
  {
    id: 9,
    date: '',
    event: 'Ритриты в Шри Датта ашраме в мае',
    done: true,
    link: 'https://telegra.ph/Priglashaem-na-tradicionnye-ritrity-v-SHri-Datta-ashram-03-27',
  },
  {
    id: 10,
    date: '19.05.2024',
    event: 'Экадаши Мохини',
    done: true,
    link: '',
  },
  {
    id: 11,
    date: '21.05.2024',
    event: 'Риши Вьяса Джаянти',
    done: true,
    link: '',
  },
  {
    id: 12,
    date: '02.06.2024',
    event: 'Экадаши Апара',
    done: true,
    link: '',
  },
  {
    id: 13,
    date: '17.06.2024',
    event: 'Экадаши Нирджала',
    done: true,
    link: '',
  },
  {
    id: 14,
    date: '02.07.2024',
    event: 'Экадаши Йогини',
    done: true,
    link: '',
  },
  {
    id: 15,
    date: '17.07.2024',
    event: 'Экадаши Падма',
    done: true,
    link: '',
  },
  {
    id: 16,
    date: '21.07.2024',
    event: 'Гуру-пурнима',
    done: true,
    link: '',
  },
  {
    id: 17,
    date: '31.07.2024',
    event: 'Экадаши Камика',
    done: false,
    link: '',
  },
  {
    id: 18,
    date: '16.08.2024',
    event: 'Экадаши Павитропана',
    done: false,
    link: '',
  },
  {
    id: 19,
    date: '29.08.2024',
    event: 'Экадаши Аннада',
    done: false,
    link: '',
  },
  {
    id: 20,
    date: '07.09.2024',
    event: 'Ганеша-чатуртхи, Шрипада Шриваллабха Джаянти',
    done: false,
    link: '',
  },
  {
    id: 21,
    date: '14.09.2024',
    event: 'Экадаши Паршва',
    done: false,
    link: '',
  },
  {
    id: 22,
    date: '28.09.2024',
    event: 'Экадаши Индира',
    done: false,
    link: '',
  },
  {
    id: 23,
    date: '03.10.2024',
    event: '03.10.2024 Осеннее Наваратри',
    done: false,
    link: '',
  },
  {
    id: 24,
    date: '05.10.2024',
    event: 'Рамалинга-джаянти',
    done: false,
    link: '',
  },
  {
    id: 25,
    date: '13.10.2024',
    event: 'Экадаши Папанкуша',
    done: false,
    link: '',
  },
  {
    id: 26,
    date: '17.10.2024',
    event: 'Валмики-джаянти',
    done: false,
    link: '',
  },
  {
    id: 27,
    date: '24.10.2024',
    event: 'Вьяса Пуджа',
    done: false,
    link: '',
  },
  {
    id: 28,
    date: '27.10.2024',
    event: 'Экадаши Рама',
    done: false,
    link: '',
  },
  {
    id: 29,
    date: '29.10.2024',
    event: 'Дханвантари-джаянти',
    done: false,
    link: '',
  },
  {
    id: 30,
    date: '01.11.2024',
    event: 'Дивали (Лакшми-пуджа)',
    done: false,
    link: '',
  },
  {
    id: 31,
    date: '12.11.2024',
    event: 'Экадаши Уттхана',
    done: false,
    link: '',
  },
  {
    id: 32,
    date: '26.11.2024',
    event: 'Экадаши Утпанна',
    done: false,
    link: '',
  },
  {
    id: 33,
    date: '11.12.2024',
    event: 'Экадаши Мокшада',
    done: false,
    link: '',
  },
  {
    id: 34,
    date: '14.12.2024',
    event: 'Даттатрея-джаянти',
    done: false,
    link: '',
  },
  {
    id: 35,
    date: '19.12.2024',
    event: 'Памбатти-джаянти',
    done: false,
    link: '',
  },
  {
    id: 36,
    date: '26.12.2024',
    event: 'Экадаши Сапхала',
    done: false,
    link: '',
  },
]
