import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer"


const openSans = Open_Sans({ subsets: ['cyrillic'] })


export const metadata: Metadata = {
  title: "Московский дхарма центр ШактиМа",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <div className='w-full h-full flex justify-center'>
          <div className='gradient' />
        </div>

        <Footer />
      </body>
    </html>
  );
}
