import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer"


const openSans = Open_Sans({ subsets: ['cyrillic'] })


export const metadata: Metadata = {
  title: "Московский дхарма центр ШактиМа",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${openSans.className} antialiased relative`}>
        <Header />
        {/* <div className=" absolute top-0 bottom-0  w-svw h-full bg-gradient-to-l blur-2xl from-white via-red-100 to-white z-[-1]" >
        </div> */}

        <div className="area absolute top-0 bottom-0 h-full w-full z-[-1]">
          <div className="flex flex-col w-full h-full blur-[108px] lg:blur-[200px] opacity-40">
            <div className="bg-red-500 h-full"></div>
            <div className="bg-orange-500 h-full"></div>
            <div className="bg-yellow-500 h-full"></div>
            <div className="bg-green-500 h-full"></div>
            <div className="bg-sky-500 h-full"></div>
            <div className="bg-blue-500 h-full"></div>
            <div className="bg-violet-500 h-full"></div>
          </div>

        </div>


        <main>
          {children}
        </main>

        {/* <div className="gradient"></div> */}
        <Footer />
      </body>
    </html>
  );
}
